/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lzApp from "./lzApp";
export type { lzApp };
import type * as oft from "./oft";
export type { oft };
