site_name: MevETH
site_description: MevETH
site_url: https://manifoldfinance.github.io/mevETH

repo_url: https://github.com/manifoldfinance/mevETH
edit_uri: edit/main/docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for dark mode
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    # Palette toggle for light mode
    - scheme: slate
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc:
      permalink: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - tables

nav:
  - index.md

extra:
  homepage: https://manifoldfinance.github.io/mevETH
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/manifoldfinance/mevETH
      name: MevETH on Github
  generator: false # hide the line "Made with Material for MkDocs"

copyright: Copyright &copy; 2023 CommodityStream, Inc.
