/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILayerZeroReceiver,
  ILayerZeroReceiverInterface,
} from "../../../contracts/interfaces/ILayerZeroReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_srcChainId",
        type: "uint16",
      },
      {
        internalType: "bytes",
        name: "_srcAddress",
        type: "bytes",
      },
      {
        internalType: "uint64",
        name: "_nonce",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "_payload",
        type: "bytes",
      },
    ],
    name: "lzReceive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILayerZeroReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): ILayerZeroReceiverInterface {
    return new Interface(_abi) as ILayerZeroReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILayerZeroReceiver {
    return new Contract(address, _abi, runner) as unknown as ILayerZeroReceiver;
  }
}
