/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMevEthShareVault,
  IMevEthShareVaultInterface,
} from "../../../contracts/interfaces/IMevEthShareVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "payRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "recoverToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMevEthShareVault__factory {
  static readonly abi = _abi;
  static createInterface(): IMevEthShareVaultInterface {
    return new Interface(_abi) as IMevEthShareVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMevEthShareVault {
    return new Contract(address, _abi, runner) as unknown as IMevEthShareVault;
  }
}
