/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMevEth,
  IMevEthInterface,
} from "../../../contracts/interfaces/IMevEth";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "shares",
        type: "uint256",
      },
    ],
    name: "convertToAssets",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMevEth__factory {
  static readonly abi = _abi;
  static createInterface(): IMevEthInterface {
    return new Interface(_abi) as IMevEthInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMevEth {
    return new Contract(address, _abi, runner) as unknown as IMevEth;
  }
}
