/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRateProvider,
  IRateProviderInterface,
} from "../../../contracts/interfaces/IRateProvider";

const _abi = [
  {
    inputs: [],
    name: "getRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRateProvider__factory {
  static readonly abi = _abi;
  static createInterface(): IRateProviderInterface {
    return new Interface(_abi) as IRateProviderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRateProvider {
    return new Contract(address, _abi, runner) as unknown as IRateProvider;
  }
}
