/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITinyMevEth,
  ITinyMevEthInterface,
} from "../../../contracts/interfaces/ITinyMevEth";

const _abi = [
  {
    inputs: [],
    name: "grantRewards",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "grantValidatorWithdraw",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ITinyMevEth__factory {
  static readonly abi = _abi;
  static createInterface(): ITinyMevEthInterface {
    return new Interface(_abi) as ITinyMevEthInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITinyMevEth {
    return new Contract(address, _abi, runner) as unknown as ITinyMevEth;
  }
}
