/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseOFTV2 } from "./BaseOFTV2";
export type { OFTCoreV2 } from "./OFTCoreV2";
export type { OFTV2 } from "./OFTV2";
