/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as errorsSol from "./Errors.sol";
export type { errorsSol };
export type { IBeaconDepositContract } from "./IBeaconDepositContract";
export type { ICommonOFT } from "./ICommonOFT";
export type { IERC20 } from "./IERC20";
export type { IERC4626 } from "./IERC4626";
export type { ILayerZeroEndpoint } from "./ILayerZeroEndpoint";
export type { ILayerZeroReceiver } from "./ILayerZeroReceiver";
export type { ILayerZeroUserApplicationConfig } from "./ILayerZeroUserApplicationConfig";
export type { IMevEth } from "./IMevEth";
export type { IMevEthShareVault } from "./IMevEthShareVault";
export type { IOFTReceiverV2 } from "./IOFTReceiverV2";
export type { IOFTV2 } from "./IOFTV2";
export type { IRateProvider } from "./IRateProvider";
export type { IStakingModule } from "./IStakingModule";
export type { ITinyMevEth } from "./ITinyMevEth";
export type { IWETH } from "./IWETH";
