// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

interface IStakingModule {
    /**
     * @dev Structure for passing information about the validator deposit data.
     * @param operator - address of the operator.
     * @param pubkey - BLS public key of the validator, generated by the operator.
     * @param withdrawal_credentials - withdrawal credentials used for generating the deposit data.
     * @param signature - BLS signature of the validator, generated by the operator.
     * @param deposit_data_root - hash tree root of the deposit data, generated by the operator.
     */
    struct ValidatorData {
        address operator;
        bytes pubkey;
        bytes32 withdrawal_credentials;
        bytes signature;
        bytes32 deposit_data_root; // more efficient to be calculated off-chain
    }

    function deposit(ValidatorData calldata data, bytes32 latestDepositRoot) external payable;

    function validators() external view returns (uint256);

    function batchMigrate(ValidatorData[] calldata batchData) external;

    function mevEth() external view returns (address);

    function VALIDATOR_DEPOSIT_SIZE() external view returns (uint256);

    // onlyAdmin Functions
    function payRewards(uint256 rewards) external;
    function payValidatorWithdraw() external;
    function recoverToken(address token, address recipient, uint256 amount) external;
    function record() external returns (uint128, uint128, uint128, uint128);
    function registerExit() external;
}
