name: Slither Analysis

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - "**.sol"
      - ".github/workflows/slither.yaml"
  pull_request:
    branches: [main, develop]

# ensure multiple CI processes are not running analysis on contracts
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  PULL_NUMBER: ${{ github.event.pull_request.number }}
  RUN_ID: ${{ github.run_id }}

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          fail-on: all
          slither-args: --checklist
          solc-version: "0.8.19"
